---
title: "Football Thoughts: Violence, Cheating, and Domestic Abuse"
author: "Harriet Mason"
---

# Understanding the spirit of foodball
I spend far too much time thinking about soccer. Unfortuantely, the things I find interesting about soccer are largely uninteresting to anyone who cares about soccer. With most sports, I am interested in the *goal* of the sport as dictated by the rules, that is, based on what is allowed or disallowed, what is this sports "ideal" version of competition"? This is often refereed to others as the "spirit" of a sport. The "spirit" of a game encompases concepts such as: What is considered cheating? Do we care about individual or collective dynamics? What makes a "good player"?, etc. Football is the most popular sport in the world, I constantly speak to statisticians who analyse the sport, players who play, coaches, but I have never engaged with someone who thinks about it similarly to me. The closest I have ever come was the coach, Vince, and captain, Jacqui, from my previous league team (RIP that team will be missed).

The thing that is most facinating about soccer is that the "culture" and "spirit" are at odds in a way that seems to be completely invisible to the communinity. This conflict creates social norms in the sport that allows for fulesThis is the first of a series of blog posts that discuss that conflict. 

# Last nights soccer game
Sometimes I will play a soccer game that leaves me *seething* for day afterwards. These games typically have three two things in common:
1) Unsportsman like behaviour, which leads to
2) An escalation of violence, that was allowed to escalate because of
3) An incompetent referee

A great example of a game that followed this problem was last nights game. 
- pushing, grabbing, holding attacking players
- The referee goes against the linesman and disallows a goal on our team because of an offside
- ball out of play, girl kicks Indee and calls her a "fucking bitch"
- The referee does not award a yellow card
- Indee argues with the girl who kicked her and asked her what her problem is
- The referee cautions indee with a yellow card
- The goalkeeper starts participating in general time wasting activities
- the referee lets her do it about 3 times before he tells her to "knock it off with that"
- Their team becomes increasingly reckless, performing several illegal tackles. On one occasion I was body slammed and thrown several meetres, the other player didnt even touch the ball. This was awarded with a free kick but no penalty for the players
- One of their players jumped on Em's foot with her heels when she did not have the ball, knocking both of them to the ground. When em gets up first she kicks the other player who is laying on the ground. 
- The referee sends Em off with a red card. The other team cheers.
- Many of my team members tell me the best thing to do in these circumstances is "ignore them"

Some people may consider this referee to be unfairly biased to the other team. That could be true, but there is no reason for this referee to take sides. Often when a referee to perceived to be taking sides, they are actually being particular in terms of what they see as a foul and what is not a foul. The small differences between my teams fouls and the other teams fouls, and how these fouls relate to a broader masculine culture, is the reason ours were punished and the other team got off scott free. To understand why this happened, we need to understand the rules and social norms of the sport.

# Law 12 – Fouls and Misconduct
Very few soccer players have ever actually read the rules of the sport. Rules in sports are typically communicated through breaking them, and then learning. This means, in most players minds, their version of the rules is the social norms of the sport. Each post in this series will discuss a different section of the laws of the game, and how the social norms in the sport lead referees and players to ignore and act against those laws. Today we are looking at what the sport considers unsportsman like behaviour, i.e. what is a foul.

## The philosiphy and spirit of the laws
Football must have Laws which keep the game fair – this is a crucial foundation of the ‘beautiful game’ and a vital feature of the ‘spirit’ of the game. The best matches are those where the referee is rarely needed because the players play with respect for each other, the match officials and the Laws. Football’s Laws are relatively simple compared to most other team sports, but as many situations are subjective and match officials are human, some decisions will inevitably be wrong or cause debate and discussion. For some people, this discussion is part of the game’s enjoyment and attraction but, whether decisions are right or wrong, the ‘spirit’ of the game requires that referees’ decisions must always be respected. All those in authority, especially coaches and team captains, have a clear responsibility to the game to respect the match officials and their decisions. The Laws cannot deal with every possible situation, so where there is no direct provision in the Laws, The IFAB expects the referee to make a decision within the ‘spirit’ of the game and the Laws – this often involves asking the question, ‘what would football want/expect?’

The Laws must also contribute to the safety and welfare of players and it is  The IFAB’s responsibility to react quickly and appropriately to support the game’s participants, through the Laws themselves, when the need arises. The Laws must also contribute to the safety and welfare of players and it is  The IFAB’s responsibility to react quickly and appropriately to support the game’s participants, through the Laws themselves, when the need arises.


## Fouls at the referee's discretion
There are several actions that are fouls, not all of them are violent. Addiitonally some fouls are automatic (think of it as a minimum sentancing), and some fouls are at the referees discretion
A direct free kick is awarded if a player commits any of the following  offences against an opponent in a manner considered by the referee to be careless, reckless or using excessive force

- charges 
- jumps at 
- kicks or attempts to kick 
- pushes 
- strikes or attempts to strike (including head-butt) 
- tackles or challenges 
- trips or attempts to trip

- Careless is when a player shows a lack of attention or consideration when making a challenge or acts without precaution. No disciplinary sanction  is needed 
- Reckless is when a player acts with disregard to the danger to,  or consequences for, an opponent and must be cautioned 
- Using excessive force is when a player exceeds the necessary use of force and/or endangers the safety of an opponent and must be sent off

## Penalty reguardless of the 

- a handball offence
  - A common misconception about handballs is that they should be awarded every time the ball touches a players hand. The FIFA rules actually explicitly state "Not every touch of a player’s hand/arm with the ball is an offence". For a hand ball to be considered a foul a player needs to:
    - a) deliberately touches the ball with their hand/arm, for example moving the hand/arm towards the ball; or
    - b) touches the ball with their hand/arm when it has made their body unnaturally bigger. A player is considered to have made their body unnaturally bigger when the position of their hand/arm is not a consequence of, or justifiable by, the player’s body movement for that specific situation

- holds an opponent
- impedes an opponent with contact 
- bites or spits at someone on the team lists or a match official 
- throws an object at the ball, an opponent or a match official, or makes contact with the ball with a held object

## Fifa outtakes
Cautionable offences A player is cautioned if guilty of: 
- delaying the restart of play 
- dissent by word or action -
 entering, re-entering or deliberately leaving the field of play without the referee’s permission 
 - failing to respect the required distance when play is restarted with a dropped ball, corner kick, free kick or throw-in 
 - persistent offences (no specific number or pattern of offences constitutes ‘persistent’) 
 - unsporting behaviour 
 - entering the referee review area (RRA) 
 - excessively using the ‘review’ (TV screen) signal
 
Cautions for unsporting behaviour There are different circumstances when a player must be cautioned for unsporting behaviour, including if a player: 
- attempts to deceive the referee, e.g. by feigning injury or pretending to have been fouled (simulation)
- changes places with the goalkeeper during play or without the referee’s permission (see Law 3) 
- commits in a reckless manner a direct free kick offence 
- handles the ball to interfere with or stop a promising attack 
- commits any other offence which interferes with or stops a promising attack, except where the referee awards a penalty kick for an offence which was an attempt to play the ball or a challenge for the ball 
- denies an opponent an obvious goal-scoring opportunity by committing an offence which was an attempt to play the ball or a challenge for the ball and the referee awards a penalty kick 
- handles the ball in an attempt to score a goal (whether or not the attempt is successful) or in an unsuccessful attempt to prevent a goal 
- makes unauthorised marks on the field of play 
- plays the ball when leaving the field of play after being given permission  to leave 
- shows a lack of respect for the game 
- initiates a deliberate trick for the ball to be passed (including from a free kick or goal kick) to the goalkeeper with the head, chest, knee etc. to circumvent the Law, whether or not the goalkeeper touches the ball with the hands; the goalkeeper is cautioned if responsible for initiating the deliberate trick 
- verbally distracts an opponent during play or at a restart 

Referees must caution players who delay the restart of play by: 
- appearing to take a throw-in but suddenly leaving it to a team-mate to take - delaying leaving the field of play when being substituted 
- excessively delaying a restart 
- kicking or carrying the ball away, or provoking a confrontation by deliberately touching the ball after the referee has stopped play 
- taking a free kick from the wrong position to force a retake

Referees must caution players who delay the restart of play by: 
- appearing to take a throw-in but suddenly leaving it to a team-mate to take 
- delaying leaving the field of play when being substituted 
- excessively delaying a restart 
- kicking or carrying the ball away, or provoking a confrontation by deliberately touching the ball after the referee has stopped play 
- taking a free kick from the wrong position to force a retake

A tackle or challenge that endangers the safety of an opponent or uses excessive force or brutality must be sanctioned as serious foul play. Any player who lunges at an opponent in challenging for the ball from the front, from the side or from behind using one or both legs, with excessive force or endangers the safety of an opponent is guilty of serious foul play.

Violent conduct is when a player uses or attempts to use excessive force or brutality against an opponent when not challenging for the ball, or against a team-mate, team official, match official, spectator or any other person, regardless of whether contact is made. In addition, a player who, when not challenging for the ball, deliberately  strikes an opponent or any other person on the head or face with the hand or arm, is guilty of violent conduct unless the force used was negligible.

Warning 
The following offences should usually result in a warning; repeated or blatant offences should result in a caution or sending-off: 
- entering the field of play in a respectful/non-confrontational manner 
- failing to cooperate with a match official e.g. ignoring an instruction/request from an assistant referee or the fourth official 
- minor/low-level disagreement (by word or action) with a decision 
- occasionally leaving the confines of the technical area without committing another offence

Caution Caution offences include (but are not limited to):
- clearly/persistently not respecting the confines of their team’s technical area - delaying the restart of play by their team 
- deliberately entering the technical area of the opposing team (non-confrontational) 
- dissent by word or action including: 
  - throwing/kicking drinks bottles or other objects 
  - action(s) which show(s) a clear lack of respect for the match official(s)  e.g. sarcastic clapping 
- entering the referee review area (RRA) 
- excessively/persistently gesturing for a red or yellow card 
- excessively showing the ‘TV signal’ for a VAR ‘review’ 
- acting in a provocative or inflammatory manner 
- persistent unacceptable behaviour (including repeated warning offences) 
- showing a lack of respect for the game

Sending-off Sending-off offences include (but are not limited to): 
- delaying the restart of play by the opposing team e.g. holding onto the ball, kicking the ball away, obstructing the movement of a player 
- deliberately leaving the technical area to:

Sending-off 
Sending-off offences include (but are not limited to): 
- delaying the restart of play by the opposing team e.g. holding onto the ball, kicking the ball away, obstructing the movement of a player 
- deliberately leaving the technical area to:

If a player who is on or off the field of play throws or kicks an object (other than the match ball) at an opposing player, or throws or kicks an object (including a ball) at an opposing substitute, substituted or sent-off player, team official, or a match official or the match ball, play is restarted with a direct free kick from the position where the object struck or would have struck the person or the ball. If this position is off the field of play, the free kick is taken on the nearest point on the boundary line; a penalty kick is awarded if this is within the offender’s penalty area.


From the simplified laws of the game
"a stopping-a-promising-attack (SPA) foul is also a reckless foul?"
A yellow card is shown to the player for being reckless, which is more serious than the tactical nature of SPA.

- so Fifa clearly explicitly states that tactical fouls are less serious than violent fouls

handball comments
- a player is hit on the hand/arm by the ball from a team-mate’s kick/header? This is not handball (unless the ball goes directly into the opponents’ goal or the player scores immediately afterwards, in which case a direct free kick is awarded to the other team).
- a player heads/kicks the ball and it then hits their own hand/arm? This is not handball (unless the ball goes directly into the opponents’ goal or the player scores immediately afterwards, in which case a direct free kick is awarded to the other team).
- a player prevents the ball from going into their own goal with their hand/arm but does not deliberately handle the ball and does not make their body unnaturally bigger? This is not handball.

## Comments
The rules clearly stipulate what is considered the spirit of the game, however the social norms of the game have changed that. 

In the social norms of the sport, technical aspects of the sport, such as handballs, are punished severly while physical violence in the sport are dismissed or ignored. In lower league soccer, it is common for a ball to bounce around in a skirmish or hit a players while they are in a jumping position, and a penalty or free kick will be awarded. This clearly goes against the rule of intentional handballs. 

The social norm version of the sport the only way you can cheat is if you touch the ball with your hands. Because touching the ball with your hands is the ONLY rule

The FIFA rules say

- the ability for the partiicpant to "fight back" is largely irrelevant. If you attack another player that should be sanctioned. Its giving "If women want equality then I should be able to hit them, because the only reason I cant hit women is because they are weak" vibes.

# The three horseman of a spiritless game
## Unsportsman behaviour
## Escalation of violence
## An incompetent referee
When I say incompetent, I specifically mean a ref that has a combination of poor foresight as well as. 


# Similarities to Domestic Violence